services:
    # ---------------------------------------
    # 1. MESSAGE BROKER (Ingestion Buffer)
    # ---------------------------------------
    kafka:
        image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
        container_name: ims-kafka
        command:
            - redpanda
            - start
            - --mode dev-container
            - --smp 1
            - --memory 1G
            - --reserve-memory 0M
            - --overprovisioned
            - --node-id 0
            - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:9094
            - --advertise-kafka-addr
              internal://kafka:9092,external://localhost:9094
        ports:
            - "9092:9092"
            - "9094:9094"
        volumes:
            - kafka_data:/var/lib/redpanda/data
        networks:
            - ims-network
        healthcheck:
            test: ["CMD-SHELL", "rpk cluster health"]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---------------------------------------
    # 2. CACHE LAYER (Debouncing & Hot-Path)
    # ---------------------------------------
    redis:
        image: redis:7-alpine
        container_name: ims-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - ims-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---------------------------------------
    # 3. DATABASE (Source of Truth)
    # ---------------------------------------
    postgres:
        image: postgres:15-alpine
        container_name: ims-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ims_db
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - ims-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d ims_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---------------------------------------
    # 4. OBSERVABILITY (Metrics & Dashboards)
    # ---------------------------------------
    prometheus:
        image: prom/prometheus:latest
        container_name: ims-prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prom_data:/prometheus
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - ims-network

    grafana:
        image: grafana/grafana:latest
        container_name: ims-grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - ims-network
        depends_on:
            - prometheus

networks:
    ims-network:
        driver: bridge

volumes:
    kafka_data:
    redis_data:
    pg_data:
    prom_data:
    grafana_data:
